name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- AJOUT 1 : INDISPENSABLE POUR COMPILER EN ARM SUR GITHUB ---
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # --- AJOUT 2 : C'est ici qu'on cr√©e l'image compatible Mac (arm64) ET PC (amd64) ---
          platforms: linux/amd64,linux/arm64
          tags: |
            jaljim55/flask:latest
            jaljim55/flask:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  update_deployment:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update image tag with sed
        run: |
          IMAGE_NAME="jaljim55/flask"
          NEW_TAG="${{ github.sha }}"
          FILE="deployment/deploy.yml"

          # Utilisation de sed pour modifier la ligne de l'image
          sed -i "s|image: $IMAGE_NAME:.*|image: $IMAGE_NAME:$NEW_TAG|g" "$FILE"

          echo "V√©rification apr√®s modification :"
          grep "image: $IMAGE_NAME" "$FILE"

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add deployment/deploy.yml

          # Commit seulement s'il y a une diff√©rence r√©elle
          if git diff --cached --quiet; then
            echo "Rien √† mettre √† jour."
          else
            git commit -m "üöÄ Deploy: update image tag to ${{ github.sha }}"
            git push origin main
          fi
